@protocol= https
@domainname= apov7.herokuapp.com
@baseUrl = {{protocol}}://{{domainname}}



GET {{baseUrl}}/quiz/category/en/3
### Route PATCH quiz/article/fr/:id

POST {{baseUrl}}/login
Content-type: application/json

{
    "email": "azerty@oclock.io",
    "password": "lesuperpasswordA45"
}

### Route POST /login

POST {{baseUrl}}/login
Content-type: application/json

{
    "email": "philipope@oclock.io",
    "password": "$2b$10$7vwYGrz2TGeyG4X8YnD9BOag9I.YKGUTJELs64qGmcK/syHu2BzTG"
}


### Route POST /register

POST {{baseUrl}}/register
Content-type: application/json

{
    "email": "azerty@oclock.io",
    "firstname": "tony",
    "lastname": "james",
    "password": "lesuperPASSWORD45"
}

### Route POST /register avec Bcrypt

POST {{baseUrl}}/register
Content-type: application/json

{
    "email": "azerty@oclock.io",
    "firstname": "tony",
    "lastname": "james",
    "password": "$2b$10$7vwYGrz2TGeyG4X8YnD9BOag9I.YKGUTJELs64qGmcK/syHu2BzTG"
}
